# Generated by Django 3.1.6 on 2021-03-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uposts', '0002_auto_20210316_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geo',
        ),
        migrations.AddField(
            model_name='address',
            name='geo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uposts.geo'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uposts.address'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='company',
        ),
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uposts.company'),
        ),
    ]
