# Generated by Django 3.1.6 on 2021-03-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uposts', '0004_auto_20210320_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uposts.users'),
        ),
    ]
